#!/bin/zsh
# Description:
# This bash script will ping a server and check if the server's IP address
# matches the desired IP address.
#
# This is simple and useful script to monitor a domain's modified A record
# that points to a new hosting provider, instead of manually pinging
# the domain until propagation is complete.
#
# The script takes two arguments:
# target_ip - the IP address of the subdomain/domain in the target hosting
#             provider to which the A record will point.
# domain_to_check - the subdomain/domain in the target hosting provider

# check if proper arguments are passed
if [ $# -ne 2 ]
then
  echo "usage: $0 <target_ip_address> <target_domain_to_check>"
  exit 1
fi

target_ip="$1"
domain_to_check="$2"
log_file="$HOME/.logs/a-record-migration-$(date '+%Y-%m-%d-%H-%M-%S')-${domain_to_check}.log"

# interval to check in minutes
interval=5

# Create the log file if it doesn't exist
touch "$log_file" || { echo "Failed to create log file: $log_file"; exit 1; }

echo "Checking for migration of ${domain_to_check} to ${target_ip} at ${interval}-minute intervals."

echo "==> Migration check started on $(date)" | tee "$log_file"

while true
do
  ip=$(ping -c 1 "$domain_to_check" | awk -F'[()]' '/^PING/{print $2}')

  if [ "$ip" = "$target_ip" ]
  then
    echo "==> Migration complete on $(date)\n--+--" | tee -a "$log_file"
    exit 0
  else
    echo "==> Still pointing to ${ip} @ $(date)"
  fi

  # Wait for the interval value in minutes
  sleep $((60 * interval))
done
