#!/bin/zsh
# Description:
# This bash script will ping a server and check if the server's IP address
# matches the desired IP address.
#
# This is simple and useful script to monitor a domain's modified A record
# that points to a new hosting provider, instead of manually pinging
# the domain until propagation is complete.
#
# The script takes two arguments:
# target_ip - the IP address of the subdomain/domain in the target hosting provider to which the A record will point.
# domain_to_check - the subdomain/domain in the target hosting provider
#
# The script can also be modified to write the update messages to a text file
# ```
# echo "Migration complete @ $(date)" >> migration_check.txt
# ```
#
# and
#
# ```
# echo "Still pointing to $ip @ $(date)" >> migration_check.txt
# ```

# check if proper arguments are passed
if [ $# -eq 0 ]; then
  echo "No target ip address or domain provided."
  echo "usage: ./migrate <target_ip_address> <target_domain_to_check>"
  exit 1
fi

clear

target_ip="$1:"
domain_to_check=$2
BOLD=$(tput bold)
NORM=$(tput sgr0)

# interval to check in minutes
interval=5

log_file=~/.logs/a-record-migration-$(date '+%Y-%m-%d-%H-%M-%S')-${domain_to_check}.log

exec 3>&1 1>>${log_file} 2>&1    # see https://stackoverflow.com/a/18462920/1870339

check="Checking for migration of ${BOLD}${domain_to_check}${NORM} to ${BOLD}${target_ip}${NORM}"

echo "${check} at ${interval}-minute intervals." 1>&3
echo "${check}" 1>&2

echo "==> Migration check started on $(date)" | tee /dev/fd/3

while true; do
  ip=$(ping -c 1 $domain_to_check | grep "64 bytes from" | awk '{print $4}')

  if [ "$ip" = "${target_ip}" ]; then
    echo "==> Migration complete on $(date)\n--+--" | tee /dev/fd/3
    exit 0
  else
    echo "==> Still pointing to ${BOLD}${ip}${NORM} @ $(date)" 1>&3
  fi

  # Wait the interval value in minutes
  sleep $((60 * interval))
done
